- name: Change Time UTC to Jakarta
  ansible.builtin.shell: timedatectl set-timezone Asia/Jakarta && date
  register: result
- debug: var=result.stdout_lines
#     INSTALL PODMAN COCKPIT
- name: "--YUM-- Install"
  dnf:
    name:
      - podman
      - nfs-utils
      - python-pip
  state: latest
  register: dnf_install
- debug:
    msg: "{{dnf_install}}"


- name: "APPLICATION [SYSTEMD] Cockpit Enable"
  run_once: true
  ansible.builtin.systemd_service:
    name: "{{item}}"
    enabled: true
    state: started
    force: true
    masked: no
  with_items:
    - podman
    - nfs-server


- name: "[DIRECTORY] Create Default Container & Logs"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{log_path}}"
    - "{{local_path}}"

- name: Create a podman network
  become_user: "{{ ansible_user }}"
  containers.podman.podman_network:
    name: "{{podman_network}}"
    recreate: true
    force: true

- name: Create secret
  become_user: "{{ ansible_user }}"
  containers.podman.podman_secret:
    state: present
    name: hidden
    data: "{{ passwd_string }}"

